# Generated by Django 4.0.4 on 2022-05-11 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0002_alter_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='mover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mover', to='backendapp.mover'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
