# Generated by Django 4.0.4 on 2022-05-11 18:32

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0006_request_image_alter_request_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='image',
        ),
        migrations.AddField(
            model_name='mover',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image'),
        ),
    ]
