# Generated by Django 4.0.4 on 2022-05-12 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0009_alter_mover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
