# Generated by Django 4.0.4 on 2022-05-12 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0011_rename_id_request_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='request_id',
            new_name='id',
        ),
    ]
