# Generated by Django 4.0.4 on 2022-05-12 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0012_rename_request_id_request_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reguser',
            name='image',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
