# Generated by Django 4.0.4 on 2022-05-12 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backendapp', '0013_reguser_image_user_bio_user_full_name_user_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.DeleteModel(
            name='RegUser',
        ),
    ]
